/**
 * Base de datos de parásitos
 * Información científica de referencia para fines educativos.
 * Fuentes consultadas: CDC (DPDx), OMS, manuales de parasitología médica.
 */

export const PARASITES = [
  {
    id: "plasmodium",
    nombre: "Plasmodium falciparum",
    comun: "Malaria / Paludismo",
    grupo: "Protozoo (Apicomplexa)",
    color: "#e63946",
    acento: "#ff6b6b",
    riesgo: "Alto",
    resumen:
      "Protozoo intracelular responsable de la forma más letal de malaria. Se transmite por la picadura del mosquito Anopheles hembra e invade los glóbulos rojos.",
    taxonomia: {
      Reino: "Protista",
      Filo: "Apicomplexa",
      Clase: "Aconoidasida",
      Orden: "Haemosporida",
      Familia: "Plasmodiidae",
      Género: "Plasmodium",
      Especie: "P. falciparum",
    },
    morfologia:
      "Las formas en anillo (trofozoítos jóvenes) miden 1–2 µm. Presenta gametocitos en forma de media luna característicos. Carece de pigmento visible en estadios tempranos.",
    transmision: [
      "Picadura del mosquito Anopheles hembra (vector biológico).",
      "Transfusiones sanguíneas contaminadas.",
      "Transmisión congénita (madre a feto).",
      "Compartir agujas contaminadas.",
    ],
    sintomas: [
      "Fiebre cíclica (cada 48 h) con escalofríos",
      "Anemia hemolítica",
      "Sudoración profusa y cefalea",
      "Malaria cerebral (casos graves)",
      "Insuficiencia renal y hepática",
    ],
    diagnostico: [
      "Frotis de sangre periférica (gota gruesa y extendido)",
      "Pruebas rápidas de antígeno (RDT)",
      "PCR para especiación",
    ],
    tratamiento: [
      "Terapia combinada basada en artemisinina (TCA)",
      "Cloroquina (en zonas sin resistencia)",
      "Atovacuona-proguanil como profilaxis",
    ],
    prevencion: [
      "Mosquiteros tratados con insecticida",
      "Control de vectores y aguas estancadas",
      "Quimioprofilaxis en viajeros",
    ],
    distribucion: "África subsahariana, Sudeste Asiático, Amazonía y Oceanía.",
    cicloVida: [
      { fase: "Esporozoítos", desc: "El mosquito inocula esporozoítos en la sangre durante la picadura." },
      { fase: "Fase hepática", desc: "Invaden hepatocitos y se multiplican formando esquizontes tisulares." },
      { fase: "Fase eritrocítica", desc: "Liberan merozoítos que infectan glóbulos rojos y los destruyen." },
      { fase: "Gametocitos", desc: "Algunos se diferencian en formas sexuales captadas por el mosquito." },
      { fase: "Esporogonia", desc: "En el mosquito se reproducen sexualmente y reinician el ciclo." },
    ],
    dato: "Causa más de 600.000 muertes anuales, en su mayoría niños menores de 5 años en África.",
  },
  {
    id: "trypanosoma",
    nombre: "Trypanosoma cruzi",
    comun: "Enfermedad de Chagas",
    grupo: "Protozoo flagelado",
    color: "#7209b7",
    acento: "#b5179e",
    riesgo: "Alto",
    resumen:
      "Protozoo flagelado hemoflagelado causante de la enfermedad de Chagas. Se transmite por las heces del insecto triatomino ('vinchuca' o 'chinche besucona').",
    taxonomia: {
      Reino: "Protista",
      Filo: "Euglenozoa",
      Clase: "Kinetoplastea",
      Orden: "Trypanosomatida",
      Familia: "Trypanosomatidae",
      Género: "Trypanosoma",
      Especie: "T. cruzi",
    },
    morfologia:
      "Forma de tripomastigote alargada (20 µm) con un flagelo y una membrana ondulante característica. Presenta un cinetoplasto prominente.",
    transmision: [
      "Heces del triatomino que penetran por la herida o mucosas.",
      "Transfusión sanguínea y trasplante de órganos.",
      "Transmisión congénita.",
      "Vía oral por alimentos contaminados.",
    ],
    sintomas: [
      "Chagoma de inoculación y signo de Romaña (edema palpebral)",
      "Fiebre y malestar en fase aguda",
      "Miocardiopatía dilatada (fase crónica)",
      "Megacolon y megaesófago",
    ],
    diagnostico: [
      "Examen microscópico de sangre (fase aguda)",
      "Serología (ELISA, IFI) en fase crónica",
      "PCR para detección de ADN del parásito",
    ],
    tratamiento: [
      "Benznidazol (primera línea)",
      "Nifurtimox (alternativa)",
      "Manejo sintomático de cardiopatía",
    ],
    prevencion: [
      "Mejora de la vivienda y fumigación",
      "Control de vectores domiciliarios",
      "Cribado de bancos de sangre",
    ],
    distribucion: "América Latina, desde México hasta Argentina y Chile.",
    cicloVida: [
      { fase: "Tripomastigote", desc: "El triatomino deposita heces con tripomastigotes metacíclicos al picar." },
      { fase: "Invasión celular", desc: "Penetran células y se transforman en amastigotes intracelulares." },
      { fase: "Multiplicación", desc: "Los amastigotes se dividen por fisión binaria en el citoplasma." },
      { fase: "Liberación", desc: "Se diferencian de nuevo en tripomastigotes que rompen la célula." },
      { fase: "Vector", desc: "El insecto ingiere tripomastigotes circulantes y reinicia el ciclo." },
    ],
    dato: "Cerca de 7 millones de personas están infectadas en el mundo, sobre todo en zonas rurales.",
  },
  {
    id: "giardia",
    nombre: "Giardia lamblia",
    comun: "Giardiasis",
    grupo: "Protozoo flagelado",
    color: "#2a9d8f",
    acento: "#43d9c4",
    riesgo: "Medio",
    resumen:
      "Protozoo flagelado que coloniza el intestino delgado. Su trofozoíto piriforme con dos núcleos recuerda una 'cara'. Causa diarrea por agua contaminada.",
    taxonomia: {
      Reino: "Protista",
      Filo: "Metamonada",
      Clase: "Trepomonadea",
      Orden: "Diplomonadida",
      Familia: "Hexamitidae",
      Género: "Giardia",
      Especie: "G. lamblia",
    },
    morfologia:
      "Trofozoíto piriforme (10–20 µm) con simetría bilateral, dos núcleos, cuatro pares de flagelos y un disco adhesivo ventral. El quiste es ovalado y resistente.",
    transmision: [
      "Ingesta de agua o alimentos contaminados con quistes.",
      "Vía fecal-oral (manos sucias, guarderías).",
      "Contacto con animales infectados.",
    ],
    sintomas: [
      "Diarrea acuosa y esteatorrea (heces grasas)",
      "Dolor abdominal y distensión",
      "Náuseas y pérdida de peso",
      "Malabsorción de nutrientes",
    ],
    diagnostico: [
      "Examen de heces (quistes y trofozoítos)",
      "Detección de antígenos (ELISA)",
      "Aspirado duodenal en casos difíciles",
    ],
    tratamiento: [
      "Metronidazol",
      "Tinidazol (dosis única)",
      "Nitazoxanida",
    ],
    prevencion: [
      "Hervir o filtrar el agua de consumo",
      "Higiene de manos rigurosa",
      "Saneamiento adecuado",
    ],
    distribucion: "Mundial, con mayor prevalencia en zonas con saneamiento deficiente.",
    cicloVida: [
      { fase: "Quiste", desc: "Se ingiere el quiste resistente presente en agua contaminada." },
      { fase: "Desenquistamiento", desc: "El ácido gástrico activa la liberación de trofozoítos en el duodeno." },
      { fase: "Colonización", desc: "Los trofozoítos se adhieren a la mucosa mediante su disco ventral." },
      { fase: "Multiplicación", desc: "Se dividen por fisión binaria longitudinal." },
      { fase: "Enquistamiento", desc: "Forman quistes que se eliminan por las heces al ambiente." },
    ],
    dato: "Es uno de los parásitos intestinales más frecuentes en humanos a nivel mundial.",
  },
  {
    id: "entamoeba",
    nombre: "Entamoeba histolytica",
    comun: "Amebiasis",
    grupo: "Protozoo ameboide",
    color: "#e76f51",
    acento: "#f4a261",
    riesgo: "Medio-Alto",
    resumen:
      "Ameba que invade la mucosa del intestino grueso provocando disentería y abscesos hepáticos. Se mueve mediante pseudópodos.",
    taxonomia: {
      Reino: "Protista",
      Filo: "Amoebozoa",
      Clase: "Archamoebae",
      Orden: "Entamoebida",
      Familia: "Entamoebidae",
      Género: "Entamoeba",
      Especie: "E. histolytica",
    },
    morfologia:
      "Trofozoíto de 15–40 µm con un único núcleo de cariosoma central. Emite pseudópodos para desplazarse y fagocitar eritrocitos (hematófago).",
    transmision: [
      "Ingesta de quistes en agua o alimentos contaminados.",
      "Vía fecal-oral.",
      "Contacto sexual oral-anal.",
    ],
    sintomas: [
      "Disentería amebiana (diarrea con sangre y moco)",
      "Dolor abdominal tipo cólico",
      "Absceso hepático amebiano",
      "Fiebre y pérdida de peso",
    ],
    diagnostico: [
      "Examen de heces seriado",
      "Serología y detección de antígenos",
      "Ecografía/TAC para abscesos",
    ],
    tratamiento: [
      "Metronidazol o tinidazol",
      "Paromomicina (amebicida luminal)",
      "Drenaje de abscesos grandes",
    ],
    prevencion: [
      "Agua potable segura",
      "Lavado de frutas y verduras",
      "Higiene personal y saneamiento",
    ],
    distribucion: "Regiones tropicales y subtropicales con saneamiento deficiente.",
    cicloVida: [
      { fase: "Quiste", desc: "Se ingiere el quiste tetranucleado resistente." },
      { fase: "Desenquistamiento", desc: "Libera trofozoítos en el intestino delgado." },
      { fase: "Colonización", desc: "Los trofozoítos colonizan el colon y pueden invadir la mucosa." },
      { fase: "Invasión", desc: "Producen lesiones en 'botón de camisa' y pueden diseminarse al hígado." },
      { fase: "Enquistamiento", desc: "Forman nuevos quistes eliminados por las heces." },
    ],
    dato: "Puede permanecer asintomática durante años antes de volverse invasiva.",
  },
  {
    id: "taenia",
    nombre: "Taenia solium",
    comun: "Teniasis / Cisticercosis",
    grupo: "Helminto (Cestodo)",
    color: "#457b9d",
    acento: "#6fa8c7",
    riesgo: "Medio-Alto",
    resumen:
      "Gusano plano segmentado ('solitaria') que vive en el intestino. Su forma larvaria puede invadir el sistema nervioso causando neurocisticercosis.",
    taxonomia: {
      Reino: "Animalia",
      Filo: "Platyhelminthes",
      Clase: "Cestoda",
      Orden: "Cyclophyllidea",
      Familia: "Taeniidae",
      Género: "Taenia",
      Especie: "T. solium",
    },
    morfologia:
      "Adulto de 2–4 metros formado por un escólex con ganchos y ventosas, un cuello y miles de proglótides. Cada proglótide grávida contiene huevos.",
    transmision: [
      "Consumo de carne de cerdo cruda con cisticercos (teniasis).",
      "Ingesta de huevos por vía fecal-oral (cisticercosis).",
      "Autoinfección.",
    ],
    sintomas: [
      "Molestias abdominales leves (teniasis)",
      "Eliminación de proglótides en heces",
      "Convulsiones y cefalea (neurocisticercosis)",
      "Lesiones quísticas en el SNC",
    ],
    diagnostico: [
      "Examen de heces (huevos y proglótides)",
      "Neuroimagen (TAC/RM) para cisticercosis",
      "Serología (EITB)",
    ],
    tratamiento: [
      "Praziquantel o niclosamida (teniasis)",
      "Albendazol (cisticercosis)",
      "Corticoides y antiepilépticos de apoyo",
    ],
    prevencion: [
      "Cocción completa de la carne de cerdo",
      "Saneamiento e higiene de manos",
      "Inspección veterinaria de la carne",
    ],
    distribucion: "América Latina, África subsahariana y Asia.",
    cicloVida: [
      { fase: "Huevos", desc: "El cerdo ingiere huevos presentes en heces humanas." },
      { fase: "Cisticercos", desc: "Las larvas migran al músculo y forman cisticercos." },
      { fase: "Ingesta", desc: "El humano come carne mal cocida con cisticercos vivos." },
      { fase: "Adulto", desc: "El escólex se fija al intestino y crece el gusano adulto." },
      { fase: "Proglótides", desc: "Libera proglótides grávidas con huevos por las heces." },
    ],
    dato: "La neurocisticercosis es la causa prevenible más común de epilepsia en el mundo.",
  },
  {
    id: "ascaris",
    nombre: "Ascaris lumbricoides",
    comun: "Ascariasis",
    grupo: "Helminto (Nematodo)",
    color: "#f4a261",
    acento: "#ffcf80",
    riesgo: "Medio",
    resumen:
      "El nematodo intestinal más grande del ser humano. Sus larvas migran por los pulmones antes de madurar en el intestino delgado.",
    taxonomia: {
      Reino: "Animalia",
      Filo: "Nematoda",
      Clase: "Chromadorea",
      Orden: "Ascaridida",
      Familia: "Ascarididae",
      Género: "Ascaris",
      Especie: "A. lumbricoides",
    },
    morfologia:
      "Gusano cilíndrico de color rosado; las hembras alcanzan 20–35 cm y los machos 15–30 cm. Extremos afilados y cutícula resistente.",
    transmision: [
      "Ingesta de huevos embrionados del suelo o alimentos.",
      "Vía fecal-oral por manos contaminadas.",
      "Verduras regadas con aguas residuales.",
    ],
    sintomas: [
      "Tos y síndrome de Löffler (migración pulmonar)",
      "Dolor abdominal y náuseas",
      "Obstrucción intestinal (cargas altas)",
      "Desnutrición en niños",
    ],
    diagnostico: [
      "Examen de heces (huevos característicos)",
      "Visualización de gusanos adultos",
      "Radiografía en obstrucciones",
    ],
    tratamiento: [
      "Albendazol o mebendazol",
      "Pamoato de pirantel",
      "Cirugía en obstrucción grave",
    ],
    prevencion: [
      "Saneamiento y letrinas adecuadas",
      "Lavado de alimentos y manos",
      "Desparasitación masiva periódica",
    ],
    distribucion: "Zonas tropicales y templadas con saneamiento deficiente.",
    cicloVida: [
      { fase: "Huevos", desc: "Se ingieren huevos embrionados presentes en el suelo." },
      { fase: "Larvas", desc: "Eclosionan en el intestino y atraviesan la pared." },
      { fase: "Migración pulmonar", desc: "Viajan por la sangre hasta los pulmones y ascienden por la tráquea." },
      { fase: "Maduración", desc: "Se degluten de nuevo y maduran en el intestino delgado." },
      { fase: "Reproducción", desc: "Las hembras producen hasta 200.000 huevos diarios eliminados por heces." },
    ],
    dato: "Una hembra puede poner más de 200.000 huevos al día durante su vida.",
  },
  {
    id: "leishmania",
    nombre: "Leishmania donovani",
    comun: "Leishmaniasis visceral",
    grupo: "Protozoo flagelado",
    color: "#06d6a0",
    acento: "#52f0c4",
    riesgo: "Alto",
    resumen:
      "Protozoo intracelular transmitido por flebótomos. La forma visceral (kala-azar) afecta bazo, hígado y médula ósea y puede ser mortal sin tratamiento.",
    taxonomia: {
      Reino: "Protista",
      Filo: "Euglenozoa",
      Clase: "Kinetoplastea",
      Orden: "Trypanosomatida",
      Familia: "Trypanosomatidae",
      Género: "Leishmania",
      Especie: "L. donovani",
    },
    morfologia:
      "Amastigote redondeado (2–5 µm) sin flagelo libre dentro de macrófagos; promastigote alargado y flagelado en el vector.",
    transmision: [
      "Picadura del flebótomo (mosca de la arena).",
      "Transfusiones y agujas compartidas (raro).",
      "Transmisión congénita ocasional.",
    ],
    sintomas: [
      "Fiebre prolongada e irregular",
      "Hepatoesplenomegalia marcada",
      "Anemia y pancitopenia",
      "Pérdida de peso y debilidad",
    ],
    diagnostico: [
      "Aspirado de médula ósea o bazo",
      "Serología (rK39) y PCR",
      "Cultivo del parásito",
    ],
    tratamiento: [
      "Anfotericina B liposomal",
      "Antimoniales pentavalentes",
      "Miltefosina oral",
    ],
    prevencion: [
      "Control de flebótomos y reservorios",
      "Mosquiteros de malla fina",
      "Repelentes e insecticidas",
    ],
    distribucion: "India, África oriental, Mediterráneo y Brasil.",
    cicloVida: [
      { fase: "Promastigote", desc: "El flebótomo inocula promastigotes al picar." },
      { fase: "Fagocitosis", desc: "Los macrófagos engloban los promastigotes." },
      { fase: "Amastigote", desc: "Se transforman en amastigotes y se multiplican dentro de la célula." },
      { fase: "Diseminación", desc: "Infectan nuevos macrófagos en bazo, hígado y médula." },
      { fase: "Vector", desc: "El flebótomo ingiere macrófagos infectados y reinicia el ciclo." },
    ],
    dato: "La forma visceral es mortal en más del 95 % de los casos si no se trata.",
  },
  {
    id: "toxoplasma",
    nombre: "Toxoplasma gondii",
    comun: "Toxoplasmosis",
    grupo: "Protozoo (Apicomplexa)",
    color: "#3a86ff",
    acento: "#6fa8ff",
    riesgo: "Medio",
    resumen:
      "Protozoo intracelular ubicuo cuyo huésped definitivo es el gato. Es especialmente peligroso durante el embarazo y en inmunodeprimidos.",
    taxonomia: {
      Reino: "Protista",
      Filo: "Apicomplexa",
      Clase: "Conoidasida",
      Orden: "Eucoccidiorida",
      Familia: "Sarcocystidae",
      Género: "Toxoplasma",
      Especie: "T. gondii",
    },
    morfologia:
      "Taquizoíto en forma de media luna (6 µm) con complejo apical. Forma quistes tisulares con bradizoítos de latencia prolongada.",
    transmision: [
      "Ingesta de ooquistes de heces de gato.",
      "Consumo de carne cruda con quistes tisulares.",
      "Transmisión congénita transplacentaria.",
    ],
    sintomas: [
      "Asintomática en inmunocompetentes",
      "Síndrome mononucleósico leve",
      "Encefalitis en inmunodeprimidos",
      "Malformaciones congénitas (toxoplasmosis fetal)",
    ],
    diagnostico: [
      "Serología (IgG/IgM)",
      "PCR en líquido amniótico",
      "Neuroimagen en encefalitis",
    ],
    tratamiento: [
      "Pirimetamina + sulfadiazina",
      "Ácido folínico de soporte",
      "Espiramicina en embarazo",
    ],
    prevencion: [
      "Cocción adecuada de la carne",
      "Higiene al manipular arena de gatos",
      "Lavado de frutas y verduras",
    ],
    distribucion: "Mundial; hasta un tercio de la población podría estar expuesta.",
    cicloVida: [
      { fase: "Ooquistes", desc: "El gato elimina ooquistes por las heces tras la fase sexual." },
      { fase: "Ingesta", desc: "Otros hospedadores ingieren ooquistes o quistes tisulares." },
      { fase: "Taquizoítos", desc: "Se multiplican rápidamente y diseminan por el organismo." },
      { fase: "Quistes", desc: "Forman quistes latentes con bradizoítos en músculo y cerebro." },
      { fase: "Hospedador definitivo", desc: "El gato se reinfecta al comer presas con quistes." },
    ],
    dato: "Puede alterar el comportamiento de los roedores para favorecer su transmisión al gato.",
  },
];

export const ESTADISTICAS = [
  { valor: "8", etiqueta: "Parásitos modelados en 3D" },
  { valor: "1.500 M+", etiqueta: "Personas afectadas por helmintos" },
  { valor: "600 K", etiqueta: "Muertes anuales por malaria" },
  { valor: "100 %", etiqueta: "Información interactiva" },
];
